"""empty message

Revision ID: 61396adc3f0d
Revises: 780739b227a7
Create Date: 2019-12-11 05:42:50.192715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61396adc3f0d'
down_revision = '780739b227a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=140), nullable=True),
    sa.Column('size', sa.String(length=140), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    op.drop_table('Item')
    # ### end Alembic commands ###
